### PR TITLE
Several fixes for the speaker directory

### LINKED ISSUE #390: Speaker Directory Doesn't Seem to Add New Speakers
There are a few of the new speakers that have been merged but they aren't showing up. For my case, since I have rights to the repo, it didn't create a PR. I tried to force a PR but the magic step of adding to the of speakers didn't happen. Any ideas how to address this? There are five speaker.md files in the project but only two appear. Not sure how this is being populated.

### PR DESCRIPTION
**Pull request by daveaglick**
Now that we're getting real speaker data, there's a few bugs that needed cleaning up (doubtful this is the last, so I'll try to keep an eye out).

Resolves #390

### CODE REVIEW

File: Analyzers/ValidateSpeakerTopics.cs [hunk 1]
```diff
@@ -66,7 +66,7 @@ protected override void AnalyzeSpeakerData(IDocument document, IAnalyzerContext
             IReadOnlyList<string> topics = document.GetList<string>(SiteKeys.Topics);
             if (topics == null || topics.Count == 0)
             {
-                context.Add(document, "No topics specified");
+                // No topics, but that's okay (if we ever want to enforce at least one topic, add an analyzer result here)
```
Comment (daveaglick) [inline Analyzers/ValidateSpeakerTopics.cs:69]: Turns out we're getting some speakers without topics, so I figure it's better to let those pass validation instead of fail the build.

File: GetBlogFeeds.cs [hunk 2]
```diff
@@ -129,7 +129,7 @@ protected override async Task<IEnumerable<IDocument>> ExecuteInputAsync(IDocumen
                 }
             }
 
-            return null;
+            return input.Yield();
```
Comment (daveaglick) [inline GetBlogFeeds.cs:132]: This is what caused the bug in #390 - we need to return the original document if there's no RSS feed or if something went wrong getting the feed.

File: SpeakerImage.cs [hunk 3]
```diff
@@ -12,7 +12,7 @@ public class SpeakerImage : SyncModule
                 ? input
                     .Clone(new MetadataItems
                     {
-                        { SiteKeys.Image, input.ContainsKey(SiteKeys.GitHub) ? input.GetString(SiteKeys.GitHub) + ".png" : "/img/dot_bot.png" }
+                        { SiteKeys.Image, input.ContainsKey(SiteKeys.GitHub) ? input.GetString(SiteKeys.GitHub).TrimEnd('/') + ".png" : "/img/dot_bot.png" }
```
Comment (daveaglick) [inline SpeakerImage.cs:15]: At least one of the new speaker files included a trailing slash for the GitHub URL - that doesn't hurt the link or any API integration, but the special `.png` extension trick doesn't like it so we've got to strip it when figuring out the image.

File: input/_partials/_head.cshtml [hunk 4]
```diff
@@ -27,7 +27,7 @@
   <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet" data-no-mirror=data-no-mirror />
   <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" data-no-mirror=data-no-mirror />
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" data-no-mirror=data-no-mirror />
-  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous" data-no-mirror=data-no-mirror />
+  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous" data-no-mirror=data-no-mirror />
```
Comment (daveaglick) [inline input/_partials/_head.cshtml:30]: Needed to bump the version of Font Awesome to get the Dev icon. Couldn't find an `integrity` value (they're heavily pushing custom bundle files now) so just left it off.

File: input/community/speakers/index.cshtml [hunk 5]
```diff
@@ -37,7 +37,7 @@ Title: Speaker Directory
                     <div class="form-group row">
                         <label class="col-sm-2 col-form-label">Filter By Topic</label>
                         <div class="col-sm-10" id="topic-filters">
-                            @foreach (string topic in OutputPages["community/speakers/*.html"].Where(x => !x.IdEquals(Document)).SelectMany(x => x.GetList<string>(SiteKeys.Topics)).Distinct().OrderBy(x => x))
+                            @foreach (string topic in OutputPages["community/speakers/*.html"].Where(x => !x.IdEquals(Document)).SelectMany(x => x.GetList<string>(SiteKeys.Topics, Array.Empty<string>())).Distinct().OrderBy(x => x))
```
Comment (daveaglick) [inline input/community/speakers/index.cshtml:40]: This threw if the speaker file didn't contain any topics since the default value for `.GetList(...)` is null when the key doesn't exist. Changed it to an empty result set so the `.SelectMany()` doesn't complain about getting a null result for one of the items (same with the language collection below).

File: input/community/speakers/shawn-wildermuth.md [hunk 6]
```diff
@@ -18,7 +18,7 @@ Topics:
   - Visual Studio Code
   - Web Development
 Blog: https://wildermuth.com
-Feed: https://wildermuth.com/rss
+Feed: http://feeds.feedburner.com/ShawnWildermuth
```
Comment (daveaglick) [inline input/community/speakers/shawn-wildermuth.md:21]: @shawnwildermuth I went ahead and changed the RSS link here to the Feedburner URL so this PR works self-contained. When you go to merge in your 301 support, feel free to change it back.

**Review by shawnwildermuth — APPROVED** [review]
