### PR TITLE
Updating Statiq and fixing remaining link validation errors

### LINKED ISSUE #552: Links with certain characters aren't generated correctly
See:
```
[WARN] Could not validate relative link: <a href="/community/speakers/micha%C3%ABl-hompus" class="speakername">Michaël Hompus</a> (ValidateRelativeLinks)
Warning: Could not validate relative link: <a href="/community/speakers/micha%C3%ABl-hompus" class="speakername">Michaël Hompus</a> (ValidateRelativeLinks)
```

Looks like the speaker page isn't matching the generated page and is incorrectly escaping the URL.

### PR DESCRIPTION
**Pull request by daveaglick**
Resolves #552

### CODE REVIEW

File: GetBlogFeeds.cs [hunk 1]
```diff
@@ -144,11 +144,11 @@ protected override async Task<IEnumerable<IDocument>> ExecuteInputAsync(IDocumen
               var speaker = input.GetString("Title");
               if (!string.IsNullOrWhiteSpace(speaker))
               {
-                context.LogWarning($"No RSS specified for {speaker}.");
+                context.LogInformation($"No RSS specified for {speaker}.");
```
Comment (daveaglick) [inline GetBlogFeeds.cs:147]: Changed these to information messages so they don't show up as PR checks since it's okay a speaker doesn't have a feed, we just want to know about it

File: input/about/election/campaign-2019/_directory.yaml [hunk 2]
```diff
@@ -0,0 +1,2 @@
+﻿Analyzers:
+  - ValidateRelativeLinks=None
```
Comment (daveaglick) [inline input/about/election/campaign-2019/_directory.yaml:2]: This whole `campaign-2019` folder had links that wouldn't validate and it appears to be here for historical purposes so I disabled the validation for these files

File: input/community/speakers/alyssa-nicoll.md [hunk 3]
```diff
@@ -8,7 +8,6 @@ Topics:
   - Diversity & Inclusion
   - JavaScript
 Blog: https://www.telerik.com/blogs/author/alyssa-nicoll
-Feed: https://feeds.feedwrench.com/all-shows-devchattv.rss
```
Comment (daveaglick) [inline input/community/speakers/alyssa-nicoll.md:11]: This feed does not appear to be valid RSS (it won't pass any of the validators) and it's 25 MB (!) as well. We could reach out and see if she's got another one, but for now I removed it since it was generating a lot of warnings.
